# Working with Numpy Library

In [20]:
import numpy as np  #For importing the library. putting np or any other name is optional

In [28]:
np_array=np.array([1,2,8,3,10,3,4,5]) #For creating an array using numpy array
np_array

array([ 1,  2,  8,  3, 10,  3,  4,  5])

In [22]:
np_array2=np_array*2
np_array2

array([ 2,  4,  6,  8, 10])

In [23]:
#We can add,subtract,multiple and divide two arrays element by element
np_array+np_array2

array([ 3,  6,  9, 12, 15])

In [24]:
np_array-np_array2

array([-1, -2, -3, -4, -5])

In [37]:
#For sorting array in descending order
np_array=np.sort(np_array)[::-1]
np_array

array([10,  8,  5,  4,  3,  3,  2,  1])

In [39]:
#For sorting the array in ascending order
np_array=np.sort(np_array)
np_array

array([ 1,  2,  3,  3,  4,  5,  8, 10])

In [42]:
#For adding,subtract,multiple and dividing a number to all elements of an array
np_array+2
np_array-2
np_array/2
np_array*2

array([ 2,  4,  6,  6,  8, 10, 16, 20])

In [ ]:
np.linspace(0,1,3, endpoint=False)

In [ ]:
np.random.randn(2,2) #For a range of random numbers

In [ ]:
np.random.randint(10,20,20)

In [43]:
np.arange(10,20,2) #For a range of equal intervalled numbers

array([10, 12, 14, 16, 18])

In [ ]:
np.arange(10,20)

In [ ]:
np.linspace(0,10,5,endpoint=True)

In [ ]:
np.eye(5,dtype=int)

In [ ]:
np.zeros(5) #For a zero and one dimensional array

In [ ]:
np.zeros(2)

In [ ]:
np.zeros((2,3),dtype=int) #For a zero and two dimensional array

In [44]:
np_range=np.random.randint(0,10,5)
np_range

array([1, 8, 9, 7, 1])

In [45]:
np_range.min()

1

In [46]:
np_range.argmin()

0

In [47]:
np_range.max()

9

In [53]:
matrix=np.array([[1,2,3],[4,5,6],[4,5,6]])

In [54]:
type(matrix)

numpy.ndarray

In [55]:
matrix[1,1]

5

In [56]:
matrix[:,1]

array([2, 5, 5])

In [57]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [58]:
matrix[:,(0,1)]

array([[1, 2],
       [4, 5],
       [4, 5]])

In [ ]:
np.random.randint()